### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by njmond** [phuongpd2k/bot-claim-ocean#1]
TypeError: Cannot read properties of undefined (reading 'mainPhrase')
    at /app/index.js:1:16002
    at process.processTicksAndRejections (node:internal/process/task_
queues:95:5)

Please help sir

**Comment by phuongpd2k** [comment]
Please update your config.json file like this

```
{
  "sendFee": false,
  "mainPhrase": "phr1 phr2 phr3 ... ...",
  "refPhrases": [
    "kata1 kata2 kata3 ... ...",
    "hira1 hira2 hira3 ... ...",
    "hira1 hira2 hira3 ... ..."
  ]
}
```
## Definition of fields:

1. sendFee: 
- if TRUE:  Automatically send GAS fee from MAIN wallet to REF wallets if REF wallet has less than 0.01 SUI
- if FALSE: do nothing

2. mainPhrases: seed phrases of the MAIN wallet (the wallet you want to focus all OCEAN on because REF wallets with 20 OCEAN or more will be sent to the MAIN wallet

3. refPhrases: seed phrases of ref wallets, declared in array form
